services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
                - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        container_name: frontend
        restart: always
        ports:
            - '127.0.0.1:14702:14702'
        networks:
            - teacoder_network
        deploy:
            resources:
                limits:
                    cpus: '0.60'
                    memory: 1200M
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'node -e ''require("http").get("http://localhost:14702/", (r) => process.exit(r.statusCode === 200 ? 0 : 1))'''
                ]
            interval: 30s
            timeout: 10s
            retries: 3

networks:
    teacoder_network:
        external: true
