FROM oven/bun:1 AS deps
WORKDIR /usr/src/app

COPY package.json bun.lock ./

RUN bun install --frozen-lockfile


FROM oven/bun:1 AS build
WORKDIR /usr/src/app

ARG NODE_ENV=production
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_COOKIE_DOMAIN
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_STORAGE_URL

ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY
ARG NEXT_PUBLIC_FPJS_API_KEY
ARG NEXT_PUBLIC_FPJS_ENDPOINT
ARG NEXT_PUBLIC_YANDEX_METRIKA_ID
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_POSTHOG_HOST

ENV NODE_ENV=${NODE_ENV}
ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
ENV NEXT_PUBLIC_COOKIE_DOMAIN=${NEXT_PUBLIC_COOKIE_DOMAIN}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_STORAGE_URL=${NEXT_PUBLIC_STORAGE_URL}

ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
ENV NEXT_PUBLIC_FPJS_API_KEY=${NEXT_PUBLIC_FPJS_API_KEY}
ENV NEXT_PUBLIC_FPJS_ENDPOINT=${NEXT_PUBLIC_FPJS_ENDPOINT}
ENV NEXT_PUBLIC_YANDEX_METRIKA_ID=${NEXT_PUBLIC_YANDEX_METRIKA_ID}
ENV NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
ENV NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
ENV NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}

COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .

RUN bun --bun run build

FROM oven/bun:1 AS release
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/.next/standalone ./
COPY --from=build /usr/src/app/.next/static ./.next/static
COPY --from=build /usr/src/app/public ./public

ENV NODE_ENV=production

EXPOSE 14701
CMD ["node", "server.js"]
