import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import { Toaster } from '../components/shared/sonner'
import { TanstackQueryProvider } from '../providers/tanstack-query-provider'

import '@/src/styles/globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang='ru' suppressHydrationWarning>
			<body className={GeistSans.variable}>
				<TanstackQueryProvider>
					{/* <ThemeProvider
						attribute='class'
						defaultTheme='dark'
						enableSystem
						disableTransitionOnChange
					> */}
					<Toaster duration={2000} />
					{children}
					{/* </ThemeProvider> */}
				</TanstackQueryProvider>
			</body>
		</html>
	)
}
