import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import { TanstackQueryProvider } from '../providers/tanstack-query-provider'

import '@/src/styles/globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang='ru'>
			<body className={GeistSans.variable}>
				<TanstackQueryProvider>{children}</TanstackQueryProvider>
			</body>
		</html>
	)
}
